baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhang-wentao.tech" # the base hostname & protocol for your site, e.g. http://example.com
#-------------------------------
# Site Settings
title: Cloud BLOG
logo: # You can add own logo. For example '/images/logo.png'.
description: Personal website and blog.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Tags"
      url: "/tags/"
    - title: "RSS"
      url: "/feed.xml"

# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed
